"""Direwolf config generation and restart, when APRS-X manages Direwolf.

The core writes its own direwolf.conf (never the user's hand-written one) and
restarts Direwolf through a systemd user unit (deploy/aprsx-direwolf.service).
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from pathlib import Path

from .config import Config

log = logging.getLogger(__name__)

DEFAULT_CONF = Path.home() / ".config/aprsx/direwolf.conf"
DEFAULT_UNIT = "aprsx-direwolf.service"

# Settings that end up in direwolf.conf; a change to any of them needs a restart.
DIREWOLF_FIELDS = ("callsign", "ssid", "audio_device", "ptt", "direwolf_kiss_port", "digipeater")


def render(config: Config) -> str:
    """The direwolf.conf for these settings.

    Beacons, messages and iGating are the core's job, so Direwolf only gets the
    modem, PTT, KISS and (optionally) the fill-in digipeater.
    """
    lines = [
        "# Generated by APRS-X from its settings. Changes here are overwritten;",
        "# edit the settings in the web UI instead.",
        "",
        f"ADEVICE {config.audio_device}",
        "CHANNEL 0",
        f"MYCALL {config.station}",
        "MODEM 1200",
    ]
    if config.ptt:
        lines.append(f"PTT {config.ptt}")
    lines += [
        "",
        f"KISSPORT {config.direwolf_kiss_port}",
        "AGWPORT 0",
    ]
    if config.digipeater:
        lines += [
            "",
            "# Fill-in digipeater: repeat WIDE1-1 once. Direwolf drops duplicates",
            "# of a packet seen in the last 30 s (DEDUPE default).",
            "DIGIPEAT 0 0 ^WIDE1-1$ ^WIDE1-1$",
        ]
    return "\n".join(lines) + "\n"


def needs_restart(old: Config, new: Config) -> bool:
    return any(getattr(old, f) != getattr(new, f) for f in DIREWOLF_FIELDS) or (
        new.direwolf_managed and not old.direwolf_managed
    )


@dataclass
class ApplyResult:
    written: bool = False
    restarted: bool = False
    error: str | None = None


class DirewolfManager:
    def __init__(self, conf_path: Path = DEFAULT_CONF, unit: str = DEFAULT_UNIT) -> None:
        self.conf_path = conf_path
        self.unit = unit

    def write(self, config: Config) -> None:
        self.conf_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.conf_path.with_suffix(".tmp")
        tmp.write_text(render(config))
        tmp.replace(self.conf_path)

    async def restart(self) -> None:
        proc = await asyncio.create_subprocess_exec(
            "systemctl", "--user", "restart", self.unit,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
        )
        out, _ = await asyncio.wait_for(proc.communicate(), 30)
        if proc.returncode != 0:
            raise RuntimeError(out.decode(errors="replace").strip() or f"exit {proc.returncode}")

    async def apply(self, config: Config, restart: bool = True) -> ApplyResult:
        result = ApplyResult()
        try:
            self.write(config)
            result.written = True
            if restart:
                await self.restart()
                result.restarted = True
                log.info("direwolf config written to %s and %s restarted",
                         self.conf_path, self.unit)
        except Exception as e:  # report to the settings page rather than failing the save
            log.warning("direwolf apply failed: %s", e)
            result.error = str(e)
        return result
